Exchange/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^stock/', include('account.urls', namespace='account')),
    re_path(r'^account/', include('django.contrib.auth.urls')),
    re_path(r'^', include('stock.urls', namespace='stock'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import re_path
from . import views


app_name = 'account'


urlpatterns = [
    re_path(r'^$', views.dashboard, name='dashboard'),
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^edit/$', views.edit, name='edit'),
]

stock/urls.py
from . import views
from django.urls import re_path


app_name = 'stock'

urlpatterns = [
   re_path(r'^$', views.index, name='index'),
   re_path(r'^sales/(?P<id>\d+)/', views.predict_sales, name='predict_sales'),
   re_path(r'^profit/(?P<id>\d+)/', views.predict_profit, name='predict_profit'),
   re_path(r'^demand/(?P<id>\d+)/', views.predict_demand, name='predict_demand'),
   re_path(r'^profit/graph/(?P<id>\d+)/', views.graphics_profit, name='graph'),
   re_path(r'^sales/graph/(?P<id>\d+)/', views.graphics_sales, name='graph_s'),
   re_path(r'^demand/graph/(?P<id>\d+)/', views.graphics_demand, name='graph_d'),
   re_path(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.detail, name='detail')
]

stock/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings


class Company(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(unique='created')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    image = models.FileField(upload_to='Images/%Y/%m/%d', null=True)
    file = models.FileField(upload_to='CSV/%Y/%m/%d')

    class Meta:
        verbose_name_plural = 'Companies'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('stock:detail', args=[self.id, self.slug])


class Investors(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, related_name='companies', on_delete=models.CASCADE, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return 'Investor {}'.format(self.user)

stock/forms.py
from django import forms
from .models import Investors


class UserInputFormSales(forms.Form):
    user_input = forms.CharField(label='Enter number of timber to predict the sales',
                                 widget=forms.NumberInput(attrs={'class': 'form-control'}),
                                 label_suffix="")


class UserInputFormProfit(forms.Form):
    user_input = forms.CharField(label='Enter sales value to predict the profit',
                                 widget=forms.NumberInput(attrs={'class': 'form-control'}),
                                 label_suffix="")


class UserInputFormDemand(forms.Form):
    user_input = forms.CharField(label='Enter supply value to predict the demand',
                                 widget=forms.NumberInput(attrs={'class': 'form-control'}),
                                 label_suffix="")


class InvestorsForm(forms.ModelForm):
    amount = forms.DecimalField(label='Amount to Invest', widget=forms.NumberInput(attrs={'class': 'form-control'}),
                                label_suffix="")

    class Meta:
        model = Investors
        fields = ('amount',)

stock/views.py
from django.shortcuts import render, get_object_or_404
from .models import Company
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import statsmodels.api as sm
from statistics import mean
from .forms import UserInputFormSales, UserInputFormProfit, UserInputFormDemand, InvestorsForm
from .graph import draw_graph


def index(request):
    return render(request, 'stock/index.html')


def detail(request, id, slug):
    company = get_object_or_404(Company, id=id, slug=slug)
    return render(request, 'stock/detail.html', {'company': company})


def predict_sales(request, id):
    company = get_object_or_404(Company, id=id)
    file = company.file
    user_value = 0
    checker = True
    data = pd.read_csv(file)
    visual = data.head()
    reg = LinearRegression()
    X = data['People'].values.reshape(-1, 1)
    y = data['Sales'].values.reshape(-1, 1)
    mean_value = np.average(y)
    print(mean_value)
    reg.fit(X, y)
    if request.method == 'POST':
        user_sales = UserInputFormSales(data=request.POST)
        invest_form = InvestorsForm(data=request.POST)
        if invest_form.is_valid():
            new_form = invest_form.save(commit=False)
            new_form.user = request.user
            new_form.company = company
            new_form.save()
        if user_sales.is_valid():
            user_value = user_sales.cleaned_data['user_input']
            checker = False

    else:
        user_sales = UserInputFormSales()
    invest_form = InvestorsForm()
    predict = reg.intercept_[0] + reg.coef_[0][0] * float(user_value)
    percentage = ((predict-mean_value)/mean_value)*100
    return render(request, 'stock/predict_sales.html', {'percentage': percentage,
                                                        'predict': predict,
                                                        'visual': visual,
                                                        'company': company,
                                                        'invest_form':invest_form,
                                                        'user_sales': user_sales,
                                                        'checker': checker})


def predict_profit(request, id):
    company = get_object_or_404(Company, id=id)
    file = company.file
    user_value = 0
    checker = True
    name = ""
    data = pd.read_csv(file)
    visual = data.head()
    reg = LinearRegression()
    X = data['Sales'].values.reshape(-1, 1)
    y = data['Profit'].values.reshape(-1, 1)
    mean_value = np.average(y)
    print(mean_value)
    reg.fit(X, y)
    if request.method == 'POST':
        user_sales = UserInputFormProfit(data=request.POST)
        invest_form = InvestorsForm(data=request.POST)
        if invest_form.is_valid():
            new_form = invest_form.save(commit=False)
            new_form.user = request.user
            new_form.company = company
            new_form.save()
        if user_sales.is_valid():
            user_value = user_sales.cleaned_data['user_input']
            checker = False

    else:
        user_sales = UserInputFormProfit()
    invest_form = InvestorsForm()
    predict = reg.intercept_[0] + reg.coef_[0][0] * float(user_value)
    percentage = ((predict - mean_value) / mean_value) * 100
    return render(request, 'stock/predict_profit.html', {'percentage': percentage,
                                                         'predict': predict,
                                                         'visual': visual,
                                                         'company': company,
                                                         'invest_form': invest_form,
                                                         'user_sales': user_sales,
                                                         'checker': checker,
                                                         'name': name})


def predict_demand(request, id):
    company = get_object_or_404(Company, id=id)
    file = company.file
    user_value = 0
    checker = True
    data = pd.read_csv(file)
    visual = data.head()
    reg = LinearRegression()
    X = data['Demand'].values.reshape(-1, 1)
    y = data['Supply'].values.reshape(-1, 1)
    mean_value = np.average(y)
    print(mean_value)
    reg.fit(X, y)
    if request.method == 'POST':
        user_sales = UserInputFormDemand(data=request.POST)
        invest_form = InvestorsForm(data=request.POST)
        if invest_form.is_valid():
            new_form = invest_form.save(commit=False)
            new_form.user = request.user
            new_form.company = company
            new_form.save()
        if user_sales.is_valid():
            user_value = user_sales.cleaned_data['user_input']
            checker = False

    else:
        user_sales = UserInputFormDemand()
    invest_form = InvestorsForm()
    predict = reg.intercept_[0] + reg.coef_[0][0] * float(user_value)
    percentage = ((predict - mean_value) / mean_value) * 100
    return render(request, 'stock/demands.html', {'percentage': percentage,
                                                  'predict': predict,
                                                  'visual': visual,
                                                  'invest_form': invest_form,
                                                  'company': company,
                                                  'user_sales': user_sales,
                                                  'checker': checker})


def investor(request, id):
    compan = get_object_or_404(Company, id=id)
    if request.method == 'POST':
        invest_form = InvestorsForm(data=request.POST)
        if invest_form.is_valid():
            new_form = invest_form.save(commit=False)
            new_form.user = request.user
            new_form.save()
    else:
        invest_form = InvestorsForm()
    return render(request, 'stock/i.html', {'invest_form': invest_form, 'compan': compan})


def graphics_profit(request, id):
    compony = get_object_or_404(Company, id=id)
    file = compony.file
    data = pd.read_csv(file)
    X = data['People'].values.reshape(-1, 1)
    y = data['Sales'].values.reshape(-1, 1)
    reg = LinearRegression()
    reg.fit(X, y)
    predictions = reg.predict(X)

    plt.figure(figsize=(16, 8))
    plt.scatter(
        data['People'],
        data['Sales'],
        c='black'
    )
    plt.plot(
        data['People'],
        predictions,
        c='blue',
        linewidth=2
    )
    plt.xlabel("Profit")
    plt.ylabel("Sales")
    plt.show()
    return render(request, 'stock/p.html', {'compony': compony})


def graphics_demand(request, id):
    compony = get_object_or_404(Company, id=id)
    file = compony.file
    data = pd.read_csv(file)
    X = data['Demand'].values.reshape(-1, 1)
    y = data['Supply'].values.reshape(-1, 1)
    reg = LinearRegression()
    reg.fit(X, y)
    predictions = reg.predict(X)

    plt.figure(figsize=(16, 8))
    plt.scatter(
        data['Demand'],
        data['Supply'],
        c='black'
    )
    plt.plot(
        data['Demand'],
        predictions,
        c='blue',
        linewidth=2
    )
    plt.xlabel("Demand")
    plt.ylabel("Supply")
    plt.show()
    return render(request, 'stock/p.html', {'compony': compony})


def graphics_sales(request, id):
    compony = get_object_or_404(Company, id=id)
    file = compony.file
    data = pd.read_csv(file)
    X = data['Sales'].values.reshape(-1, 1)
    y = data['Profit'].values.reshape(-1, 1)
    reg = LinearRegression()
    reg.fit(X, y)
    predictions = reg.predict(X)

    plt.figure(figsize=(16, 8))
    plt.scatter(
        data['Sales'],
        data['Profit'],
        c='black'
    )
    plt.plot(
        data['Sales'],
        predictions,
        c='blue',
        linewidth=2
    )
    plt.xlabel("Sales")
    plt.ylabel("Profit")
    plt.show()
    return render(request, 'stock/s.html', {'compony': compony})

stock/templates/stock/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <title>{% block title %}Title {% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'stock/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'stock/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'stock/css/animate.css' %}">
    <link href="{% static 'stock/css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'stock/css/style.css' %}" rel="stylesheet"/>
    <!-- =======================================================
      Theme Name: Company
      Theme URL: https://bootstrapmade.com/company-free-html-bootstrap-template/
      Author: BootstrapMade
      Author URL: https://bootstrapmade.com
    ======================================================= -->
</head>

<body>
<header>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target=".navbar-collapse.collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-brand">
                        <a href="{% url 'stock:index' %}"><h1><span>Com</span>pany</h1></a>
                    </div>
                </div>

                <div class="navbar-collapse collapse">
                    <div class="menu">
                        <ul class="nav nav-tabs" role="tablist">
                            {% if request.user.is_authenticated %}
                            <li><a>Hello {{request.user.username}}</a></li>
                            <li><a href="{% url 'account:dashboard' %}"><i class="fa fa-user-o"></i> My Dashboard</a></li>
                            <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> Logout</a></li>
                            {% else %}
                            <li><a href="{% url 'login' %}"><i class="fa fa-sign-in"></i> Login</a></li>
                            <li><a href="{% url 'account:register' %}"><i class="fa fa-user-plus"></i> Sign Up</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>

{% block body %}

{% endblock %}

<section id="conatcat-info">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="media contact-info wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                    <div class="pull-left">
                        <i class="fa fa-phone"></i>
                    </div>
                    <div class="media-body">
                        <h2>Have a question or need a custom quote?</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                            labore dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation +0123 456 70
                            80</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/.container-->
</section>
<!--/#conatcat-info-->

<footer>
    <div class="footer">
        <div class="container">
            <div class="social-icon">
                <div class="col-md-4">
                    <ul class="social-network">
                        <li><a href="#" class="fb tool-tip" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#" class="twitter tool-tip" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#" class="gplus tool-tip" title="Google Plus"><i class="fa fa-google-plus"></i></a>
                        </li>
                        <li><a href="#" class="linkedin tool-tip" title="Linkedin"><i class="fa fa-linkedin"></i></a>
                        </li>
                        <li><a href="#" class="ytube tool-tip" title="You Tube"><i class="fa fa-youtube-play"></i></a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="col-md-4 col-md-offset-4">
                <div class="copyright">
                    &copy; Company Theme. All Rights Reserved.
                    <div class="credits">
                        <!--
                          All the links in the footer should remain intact.
                          You can delete the links only if you purchased the pro version.
                          Licensing information: https://bootstrapmade.com/license/
                          Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Company
                        -->
                        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a></div>
                </div>
            </div>
        </div>

        <div class="pull-right">
            <a href="#home" class="scrollup"><i class="fa fa-angle-up fa-3x"></i></a>
        </div>
    </div>
</footer>


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'stock/js/jquery-2.1.1.min.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'stock/js/bootstrap.min.js' %}"></script>
<script src="{% static 'stock/js/jquery.prettyPhoto.js' %}"></script>
<script src="{% static 'stock/js/jquery.isotope.min.js' %}"></script>
<script src="{% static 'stock/js/wow.min.js' %}"></script>
<script src="{% static 'stock/js/functions.js' %}"></script>

</body>

</html>

stock/templates/stock/d.html
{% extends 'stock/base.html' %}

{% block title %}Company detail Analysis {% endblock %}

{% block body %}
<div class="container">
    <div class="panel panel-default col-md-4">
        <a href="{{company.get_absolute_url}}">
            <div class="panel-body img">
                <img src="{{compony.image.url}}" class="img-responsive zoom">
            </div>
        </a>
        <hr>
        <div class="panel-header">
            <h4 style="text-align:center"> {{compony.name}}</h4>
        </div>
    </div>

    <div class="col-md-3">

        <a style="display:block; margin-bottom:20px" href="{% url 'stock:graph_d' compony.id %}" role="button" class="btn btn-primary">Draw graph</a>
    </div>
</div>


{% endblock %}

stock/templates/stock/demands.html
{% extends 'stock/base.html' %}

{% block title %} Predict Demand {% endblock %}

{% block body %}
<div class="container">
    <div class="panel panel-default col-md-4">
        <a href="{{company.get_absolute_url}}">
            <div class="panel-body img">
                <img src="{{company.image.url}}" class="img-responsive zoom">
            </div>
        </a>
        <hr>
        <div class="panel-header">
            <h4 style="text-align:center"> {{company.name}}</h4>
        </div>
    </div>

    <div class="col-md-6">
        <h1 style="text-align:center">Predict Demand</h1>
        <hr>
        <form method="post" action=".">
            {% csrf_token %}
            {{user_sales.as_p}}
            <input type="submit" value="Predict" class="btn btn-success">
        </form>
        {% if checker %}
        <p style="font-style:italic">Your predictions will appear</p>
        {% else %}
        <p>The predicted demand value is <span style="color:blue">{{predict}}</span></p>
        <p>The percentage increase of the demand is <span style="color:green">{{percentage}}%</span></p>
        {% if percentage > 5 %}
        <p style="font-weight:bold">You can invest</p>
        {% else %}
        <p style="font-weight:bold">It is risky to invest</p>
        {% endif %}
        {% endif %}
    </div>
    <div class="col-md-2" style="margin-top:20px">
        <a href="" role="button" class="btn btn-success" data-toggle="modal" data-target="#pop">Invest on this
            company</a>
        <div class="modal fade" id="pop">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h2 class="modal-title">Invest</h2>
                    </div>
                    <div class="modal-body">
                        <form role="form" method="post">
                            {% csrf_token %}
                            {{invest_form.as_p}}
                            <input type="submit" class="btn btn-success" value="Invest">
                        </form>

                    </div>
                </div>
            </div>
        </div>
        <a href="{% url 'stock:graph_d' company.id %}" role="button" class="btn btn-primary">View graph</a>
    </div>
</div>

{% endblock %}

stock/templates/stock/detail.html
{% extends 'stock/base.html' %}

{% block title %}Company detail Analysis {% endblock %}

{% block body %}
<div class="container">
    <div class="panel panel-default col-md-4">
        <a href="{{company.get_absolute_url}}">
            <div class="panel-body img">
                <img src="{{company.image.url}}" class="img-responsive zoom">
            </div>
        </a>
        <hr>
        <div class="panel-header">
            <h4 style="text-align:center"> {{company.name}}</h4>
        </div>
    </div>

    <div class="col-md-3">

        <a style="display:block; margin-bottom:20px" href="{% url 'stock:predict_sales' company.id %}" role="button" class="btn btn-primary">Predict Sales</a>
        <a style="display:block;  margin-bottom:20px" href="{%url 'stock:predict_profit' company.id %}" role="button" class="btn btn-success">Predict Profit</a>
        <a style="display:block;  margin-bottom:20px" href="{%url 'stock:predict_demand' company.id %}" role="button" class="btn btn-info">Predict Demand</a>
    </div>
</div>


{% endblock %}

stock/templates/stock/index.html
{% extends 'stock/base.html' %}

{% block title %} Index {% endblock %}

{% block body %}
{% load static %}
<section id="main-slider" class="no-margin">
    <div class="carousel slide">
        <div class="carousel-inner">
            <div class="item active" style="background-image: url({% static 'stock/images/slider/bg1.jpg' %})">
                <div class="container">
                    <div class="row slide-margin">
                        <div class="col-sm-6">
                            <div class="carousel-content">
                                <h2 class="animation animated-item-1">Welcome <span>Company</span></h2>
                                <p class="animation animated-item-2">Accusantium doloremque laudantium totam rem
                                    aperiam, eaque ipsa...</p>
                                <a class="btn-slide animation animated-item-3" href="#">Read More</a>
                            </div>
                        </div>

                        <div class="col-sm-6 hidden-xs animation animated-item-4">
                            <div class="slider-img">
                                <img src="{% static 'stock/images/slider/img3.png' %}" class="img-responsive">
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <!--/.item-->
        </div>
        <!--/.carousel-inner-->
    </div>
    <!--/.carousel-->
</section>
<!--/#main-slider-->


{% endblock %}

stock/templates/stock/p.html
{% extends 'stock/base.html' %}

{% block title %}Company detail Analysis {% endblock %}

{% block body %}
<div class="container">
    <div class="panel panel-default col-md-4">
        <a href="{{company.get_absolute_url}}">
            <div class="panel-body img">
                <img src="{{compony.image.url}}" class="img-responsive zoom">
            </div>
        </a>
        <hr>
        <div class="panel-header">
            <h4 style="text-align:center"> {{compony.name}}</h4>
        </div>
    </div>

    <div class="col-md-3">

        <a style="display:block; margin-bottom:20px" href="{% url 'stock:graph' compony.id %}" role="button" class="btn btn-primary">Draw graph</a>
    </div>
</div>


{% endblock %}

stock/templates/stock/predict_profit.html
{% extends 'stock/base.html' %}

{% block title %} Predict Profit {% endblock %}

{% block body %}
<div class="container">
    <div class="panel panel-default col-md-4">
        <a href="{{company.get_absolute_url}}">
            <div class="panel-body img">
                <img src="{{company.image.url}}" class="img-responsive zoom">
            </div>
        </a>
        <hr>
        <div class="panel-header">
            <h4 style="text-align:center"> {{company.name}}</h4>
        </div>
    </div>

    <div class="col-md-5">
        <h1 style="text-align:center">Predict Profit</h1>
        <hr>
        <form method="post" action=".">
            {% csrf_token %}
            {{user_sales.as_p}}
            <input type="submit" value="Predict" class="btn btn-success">
        </form>
        {% if checker %}
        <p style="font-style:italic">Your predictions will appear</p>
        {% else %}
        <p>The predicted profit value is <span style="color:blue">{{predict}}</span></p>
        <p>The percentage increase of the profit is <span style="color:green">{{percentage}}%</span></p>
        {% if percentage > 5 %}
        <p style="font-weight:bold">You can invest</p>
        {% else %}
        <p style="font-weight:bold">It is risky to invest</p>
        {% endif %}
        {% endif %}
    </div>
    <div class="col-md-2" style="margin-top:20px">
        <a href="" role="button" class="btn btn-success" data-toggle="modal" data-target="#pop" >Invest on this company</a>
        <div class="modal fade" id="pop">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h2 class="modal-title">Invest</h2>
                    </div>
                    <div class="modal-body">
                        <form role="form" method="post">
                            {% csrf_token %}
                            {{invest_form.as_p}}
                            <input type="submit" class="btn btn-success" value="Invest">
                        </form>

                    </div>
                </div>
            </div>
        </div>
        <a href="{% url 'stock:graph' company.id %}" role="button" class="btn btn-primary">View graph</a>
    </div>
</div>

{% endblock %}

stock/templates/stock/predict_sales.html
{% extends 'stock/base.html' %}

{% block title %} Predict Sales {% endblock %}

{% block body %}
<div class="container">
    <div class="panel panel-default col-md-4">
        <a href="{{company.get_absolute_url}}">
            <div class="panel-body img">
                <img src="{{company.image.url}}" class="img-responsive zoom">
            </div>
        </a>
        <hr>
        <div class="panel-header">
            <h4 style="text-align:center"> {{company.name}}</h4>
        </div>
    </div>

    <div class="col-md-6">
        <h1 style="text-align:center">Predict Sales</h1>
        <hr>
        <form method="post" action=".">
            {% csrf_token %}
            {{user_sales.as_p}}
            <input type="submit" value="Predict" class="btn btn-success">
        </form>
        {% if checker %}
        <p style="font-style:italic">Your predictions will appear</p>
        {% else %}
        <p>The predicted sales value is <span style="color:blue">{{predict}}</span></p>
        <p>The percentage increase of the sales is <span style="color:green">{{percentage}}%</span></p>
        {% if percentage > 5 %}
        <p style="font-weight:bold">You can invest</p>
        {% else %}
        <p style="font-weight:bold">It is risky to invest</p>
        {% endif %}
        {% endif %}
    </div>
    <div class="col-md-2" style="margin-top:20px">
        <a href="" role="button" class="btn btn-success" data-toggle="modal" data-target="#pop" >Invest on this company</a>
        <div class="modal fade" id="pop">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h2 class="modal-title">Invest</h2>
                    </div>
                    <div class="modal-body">
                        <form role="form" method="post">
                            {% csrf_token %}
                            {{invest_form.as_p}}
                            <input type="submit" class="btn btn-success" value="Invest">
                        </form>

                    </div>
                </div>
            </div>
        </div>
        <a href="{% url 'stock:graph_s' company.id %}" role="button" class="btn btn-primary">View graph</a>
    </div>
</div>
{% endblock %}

stock/templates/stock/s.html
{% extends 'stock/base.html' %}

{% block title %}Company detail Analysis {% endblock %}

{% block body %}
<div class="container">
    <div class="panel panel-default col-md-4">
        <a href="{{company.get_absolute_url}}">
            <div class="panel-body img">
                <img src="{{compony.image.url}}" class="img-responsive zoom">
            </div>
        </a>
        <hr>
        <div class="panel-header">
            <h4 style="text-align:center"> {{compony.name}}</h4>
        </div>
    </div>

    <div class="col-md-3">

        <a style="display:block; margin-bottom:20px" href="{% url 'stock:graph_s' compony.id %}" role="button" class="btn btn-primary">Draw graph</a>
    </div>
</div>


{% endblock %}